#libraries
library(readr)
library(lme4)
library(lmerTest)
library(ggplot2)
library(dplyr)
library(tidyr)
library(tibble)
library(xtable)
library(Hmisc)
library(nnet)
library(reshape2)
library(ggbiplot)
library(corrplot)
library(lsmeans)
library(factoextra)
library(ggfortify)
library(compareGroups)
library(RColorBrewer)
library(MASS)
library(effects)
library(VIM)
library(mice)
library(multcompView)
library(stargazer)
library(lattice)
library(gridExtra)
library(car)
library(ggplot2)
library(GGally)
require(ggpubr)
require(tidyverse)
require(corrplot)
library(tidyr)
library(emmeans)


#Define subsets
df_plac<- subset(df, med_type=='Placebo')
df_nalt <- subset (df, med_type=='Naltrexone')

#Mixed-effects logistic regression models
m1 <- (glmer(Rating ~ ContextNum*EmotionNum + (1|Participant/Order), family=binomial, df_plac))
summary(m1)
car::Anova(m1, "III")
vif.lme(m1 )
plot(emmeans(m1,  ~ ContextNum*EmotionNum), horiz = F)

m2 <- (glmer(Rating ~ ContextNum*EmotionNum + (1|Participant/Order), family=binomial, df_nalt))
summary(m2)
car::Anova(m2, "III")
vif.lme(m2)
plot(emmeans(m2, ~ ContextNum*EmotionNum), horiz = F)

m3 <- (glmer(Rating ~ Context*EmotionNum + med_type(1|Participant/Order), family=binomial, df))
summary(m3)
car::Anova(m3, "III")
vif.lme(m3)